version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nest-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - my-network

volumes:
  redis_data:

networks:
  my-network:
    driver: bridge
